### ISSUE TITLE
Support messages alerts

### ISSUE THREAD

**Issue by baudev** [quelqun007/NexecureScheduler#10]
Add messages alerts.

It could be interesting sending messages when the alarm can't be enabled or disabled.

Example of library for sending messages by the operator Free: [https://www.npmjs.com/package/free-mobile-sms-api ](https://www.npmjs.com/package/free-mobile-sms-api)

**Comment by quelqun007** [comment]
Implemented in commit:4d3ae6c25f0f8fb1e874bffc5fa97af887d80378
